export const distributors = [
  // ── Desert Road, Al-Nahda & Al-Bangar sector ──
  {
    id: 'rep-shaheen',
    name: 'Eng. Mohamed Shaheen',
    nameAr: 'م. محمد شاهين',
    region: 'Desert Road, Al-Nahda & Al-Bangar',
    regionAr: 'الصحراوي والنهضة والبنجر',
    wilaya: 'Desert Road, Al-Nahda & Al-Bangar',
    wilayaAr: 'الصحراوي والنهضة والبنجر',
    address: 'Desert Road, Al-Nahda & Al-Bangar area',
    addressAr: 'منطقة الصحراوي والنهضة والبنجر',
    phone: '01203420020',
    whatsapp: '201203420020',
    lat: 30.68,
    lng: 30.1,
  },
  {
    id: 'rep-elshafei',
    name: 'Eng. Mohamed El-Shafei',
    nameAr: 'م. محمد الشافعي',
    region: 'Desert Road, Al-Nahda & Al-Bangar',
    regionAr: 'الصحراوي والنهضة والبنجر',
    wilaya: 'Desert Road, Al-Nahda & Al-Bangar',
    wilayaAr: 'الصحراوي والنهضة والبنجر',
    address: 'Desert Road, Al-Nahda & Al-Bangar area',
    addressAr: 'منطقة الصحراوي والنهضة والبنجر',
    phone: '01014078788',
    whatsapp: '201014078788',
    lat: 30.7,
    lng: 30.12,
  },
  {
    id: 'rep-ahmedsaad',
    name: 'Eng. Ahmed Saad',
    nameAr: 'م. أحمد سعد',
    region: 'Desert Road, Al-Nahda & Al-Bangar',
    regionAr: 'الصحراوي والنهضة والبنجر',
    wilaya: 'Desert Road, Al-Nahda & Al-Bangar',
    wilayaAr: 'الصحراوي والنهضة والبنجر',
    address: 'Desert Road, Al-Nahda & Al-Bangar area',
    addressAr: 'منطقة الصحراوي والنهضة والبنجر',
    phone: '01006112430',
    whatsapp: '201006112430',
    lat: 30.66,
    lng: 30.08,
  },
  // ── Upper Egypt sector ──
  {
    id: 'rep-amr',
    name: 'Eng. Amr',
    nameAr: 'م. عمرو',
    region: 'Upper Egypt',
    regionAr: 'الصعيد',
    wilaya: 'Upper Egypt',
    wilayaAr: 'الصعيد',
    address: 'Upper Egypt sector',
    addressAr: 'قطاع الصعيد',
    phone: '01001380132',
    whatsapp: '201001380132',
    lat: 27.1783,
    lng: 31.1859,
  },
  // ── Delta sector ──
  {
    id: 'rep-wassim',
    name: 'Eng. Wassim El-Hadary',
    nameAr: 'م. وسيم الحضري',
    region: 'Delta',
    regionAr: 'الدلتا',
    wilaya: 'Delta',
    wilayaAr: 'الدلتا',
    address: 'Delta sector',
    addressAr: 'قطاع الدلتا',
    phone: '01011922492',
    whatsapp: '201011922492',
    lat: 30.7865,
    lng: 31.0004,
  },
  // ── Western Region, Al-Bostan & Peat Moss ──
  {
    id: 'rep-amgad',
    name: 'Eng. Amgad',
    nameAr: 'م. أمجد',
    region: 'Western Region & Al-Bostan',
    regionAr: 'المنطقة الغربية والبستان',
    wilaya: 'Western Region & Al-Bostan',
    wilayaAr: 'المنطقة الغربية والبستان',
    address: 'Western Region & Al-Bostan — responsible for all types of peat moss',
    addressAr: 'المنطقة الغربية والبستان — المسؤول عن البيتموس بأنواعه',
    phone: '01002172597',
    whatsapp: '201002172597',
    lat: 30.6,
    lng: 30.0,
  },
]
