export const distributors = [
  {
    id: 'dist-hq-giza',
    name: 'Al Kalthoum Group — Head Office',
    nameAr: 'مجموعة الكلثوم — المقر الرئيسي',
    region: 'Giza',
    regionAr: 'الجيزة',
    wilaya: 'Giza',
    wilayaAr: 'الجيزة',
    address: 'Egypt–Alexandria Desert Road, Giza',
    addressAr: 'طريق مصر إسكندرية الصحراوي، الجيزة',
    phone: '+20 109 330 9222',
    whatsapp: '201093309222',
    lat: 30.0131,
    lng: 31.2089,
  },
  {
    id: 'dist-cairo',
    name: 'Al Kalthoum Distribution — Cairo',
    nameAr: 'الكلثوم للتوزيع — القاهرة',
    region: 'Cairo',
    regionAr: 'القاهرة',
    wilaya: 'Cairo',
    wilayaAr: 'القاهرة',
    address: 'New Cairo, First Settlement',
    addressAr: 'التجمع الأول، القاهرة الجديدة',
    phone: '+20 109 330 9222',
    whatsapp: '201093309222',
    lat: 30.0333,
    lng: 31.4913,
  },
  {
    id: 'dist-alexandria',
    name: 'Al Kalthoum Distribution — Alexandria',
    nameAr: 'الكلثوم للتوزيع — الإسكندرية',
    region: 'Alexandria',
    regionAr: 'الإسكندرية',
    wilaya: 'Alexandria',
    wilayaAr: 'الإسكندرية',
    address: 'Amreya Industrial Zone, Alexandria',
    addressAr: 'المنطقة الصناعية بعمرية، الإسكندرية',
    phone: '+20 109 330 9222',
    whatsapp: '201093309222',
    lat: 31.2001,
    lng: 29.9187,
  },
  {
    id: 'dist-delta',
    name: 'Al Kalthoum Distribution — Delta',
    nameAr: 'الكلثوم للتوزيع — الدلتا',
    region: 'Gharbia',
    regionAr: 'الغربية',
    wilaya: 'Tanta',
    wilayaAr: 'طنطا',
    address: 'Industrial Zone, Tanta',
    addressAr: 'المنطقة الصناعية، طنطا',
    phone: '+20 109 330 9222',
    whatsapp: '201093309222',
    lat: 30.7865,
    lng: 31.0004,
  },
  {
    id: 'dist-upper-egypt',
    name: 'Al Kalthoum Distribution — Upper Egypt',
    nameAr: 'الكلثوم للتوزيع — الصعيد',
    region: 'Assiut',
    regionAr: 'أسيوط',
    wilaya: 'Assiut',
    wilayaAr: 'أسيوط',
    address: 'New Assiut Industrial City',
    addressAr: 'مدينة أسيوط الجديدة الصناعية',
    phone: '+20 109 330 9222',
    whatsapp: '201093309222',
    lat: 27.1783,
    lng: 31.1859,
  },
  {
    id: 'dist-canal',
    name: 'Al Kalthoum Distribution — Canal Zone',
    nameAr: 'الكلثوم للتوزيع — قناة السويس',
    region: 'Ismailia',
    regionAr: 'الإسماعيلية',
    wilaya: 'Ismailia',
    wilayaAr: 'الإسماعيلية',
    address: 'Ismailia Agricultural Services Zone',
    addressAr: 'منطقة الخدمات الزراعية، الإسماعيلية',
    phone: '+20 109 330 9222',
    whatsapp: '201093309222',
    lat: 30.5965,
    lng: 32.2715,
  },
]
